//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 03. 17. 11:24:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Macska
{
    public partial class Macska {

        public Macska()
        {
            OnCreated();
        }

        public int CatId { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public string Gender { get; set; }

        public int BreedId { get; set; }


        public virtual Fajtak Fajta { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
