//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 03. 17. 11:24:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Macska
{
    public partial class Fajtak {

        public Fajtak()
        {
            this.Macskak = new List<Macska>();
            OnCreated();
        }

        public int BreedId { get; set; }

        public string BreedName { get; set; }

        public decimal AvWeight { get; set; }

        public string LifeSpan { get; set; }

        public string Description { get; set; }

        public string FurLenght { get; set; }

        public string Personality { get; set; }

        public string ImgPath { get; set; }

        public int CountryId { get; set; }


        public virtual Szarmazas Szarmazas { get; set; }


        public virtual IList<Macska> Macskak { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
