//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 03. 17. 11:24:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Macska
{

    public partial class cnModel : DbContext
    {

        public cnModel() :
            base()
        {
            OnCreated();
        }

        public cnModel(DbContextOptions<cnModel> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Szarmazas> Szarmazas
        {
            get;
            set;
        }

        public virtual DbSet<Fajtak> Fajtaks
        {
            get;
            set;
        }

        public virtual DbSet<Macska> Macskas
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.SzarmazasMapping(modelBuilder);
            this.CustomizeSzarmazasMapping(modelBuilder);

            this.FajtakMapping(modelBuilder);
            this.CustomizeFajtakMapping(modelBuilder);

            this.MacskaMapping(modelBuilder);
            this.CustomizeMacskaMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Szarmazas Mapping

        private void SzarmazasMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Szarmazas>().ToTable(@"Country");
            modelBuilder.Entity<Szarmazas>().Property(x => x.CountryId).HasColumnName(@"CountryId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Szarmazas>().Property(x => x.CountryName).HasColumnName(@"CountryName").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Szarmazas>().Property(x => x.Continent).HasColumnName(@"Continent").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Szarmazas>().HasKey(@"CountryId");
        }

        partial void CustomizeSzarmazasMapping(ModelBuilder modelBuilder);

        #endregion

        #region Fajtak Mapping

        private void FajtakMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Fajtak>().ToTable(@"Breed");
            modelBuilder.Entity<Fajtak>().Property(x => x.BreedId).HasColumnName(@"BreedId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.BreedName).HasColumnName(@"BreedName").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.AvWeight).HasColumnName(@"AvWeight").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.LifeSpan).HasColumnName(@"LifeSpan").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.Description).HasColumnName(@"Description").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.FurLenght).HasColumnName(@"FurLenght").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.Personality).HasColumnName(@"Personality").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.ImgPath).HasColumnName(@"ImgPath").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().Property(x => x.CountryId).HasColumnName(@"CountryId").ValueGeneratedNever();
            modelBuilder.Entity<Fajtak>().HasKey(@"BreedId");
        }

        partial void CustomizeFajtakMapping(ModelBuilder modelBuilder);

        #endregion

        #region Macska Mapping

        private void MacskaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Macska>().ToTable(@"Cat");
            modelBuilder.Entity<Macska>().Property(x => x.CatId).HasColumnName(@"CatId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Macska>().Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Macska>().Property(x => x.Age).HasColumnName(@"Age").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Macska>().Property(x => x.Gender).HasColumnName(@"Gender").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Macska>().Property(x => x.BreedId).HasColumnName(@"BreedId").ValueGeneratedNever();
            modelBuilder.Entity<Macska>().HasKey(@"CatId");
        }

        partial void CustomizeMacskaMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Szarmazas>().HasMany(x => x.OriginCountryId).WithOne(op => op.Szarmazas).HasForeignKey(@"CountryId").IsRequired(true);

            modelBuilder.Entity<Fajtak>().HasOne(x => x.Szarmazas).WithMany(op => op.OriginCountryId).HasForeignKey(@"CountryId").IsRequired(true);
            modelBuilder.Entity<Fajtak>().HasMany(x => x.Macskak).WithOne(op => op.Fajta).HasForeignKey(@"BreedId").IsRequired(true);

            modelBuilder.Entity<Macska>().HasOne(x => x.Fajta).WithMany(op => op.Macskak).HasForeignKey(@"BreedId").IsRequired(true);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
